<?php

return [
    'msg' => [
        "user-not-found" => "User Tidak Ditemukan",
        "refresh-token-expired" => "Sesi anda telah habis. Silahkan login kembali.",
        "invalid-refresh-token" => "Sesi anda telah habis. Silahkan login kembali.",
        "token-expired" => "Token Expired",
        "password-not-found" => "Password tidak ditemukan",
        "new-password-must-be-different" => "Password baru harus berbeda dengan password sebelumnya",
        "invalid-credentials" => 'Email atau username dan password tidak cocok',
        "invalid-function-arguments" => 'Invalid function arguments',
        "end-date-before-start-date" => 'Tanggal akhir harus setelah tanggal mulai',
        "access-denied" => 'Access ditolak',
        "invalid-input" => 'Input tidak valid',
        "duplicate-voucher-code" => 'Kode voucher sudah pernah diajukan',
        "voucher-code-not-found" => 'Kode voucher tidak ditemukan',
        "invalid-enum" => 'Enum tidak valid',
        "invalid-team-member-count" => 'Jumlah anggota tim tidak valid',
        'db-fail-to-save' => 'Tidak dapat menyimpan, mohon coba lagi dalam 30 detik',
        'user-exists' => 'Pengguna sudah ada',
        "team-not-found" => "Tim tidak ditemukan",
        "have-paid" => "Anda sudah membayar",
        "duplicate-email-team" => "Email di dalam tim tidak boleh kembar",
        "voucher-limit-reached" => "Voucher telah memenuhi batas maksimum",
        "team-has-applied-voucher" => "Voucher sudah pernah digunakan",
        "team-has-uploaded-bukti-bayar" => "Voucher tidak dapat digunakan sebab tim anda telah mengupload bukti bayar",
        "invalid-voucher-apply-date" => "Masa berlaku voucher telah selesai",
        "no-access-to-team" => "Akses harus melalui ketua tim",
        "user-has-active-ticket" => "Anda telah memiliki tiket",
        "failed-to-save-file" => "Gagal menyimpan file",
		"payment-closed" => "Pembayaran sudah tidak dapat dilakukan karena pendaftaran sudah ditutup",
		"payment-verified" => "Bukti pembayaran sudah diverifikasi",
    ],
    'code' => [
        'default' => 1000,
        "user-not-found" => 1001,
        "refresh-token-expired" => 1002,
        "invalid-refresh-token" => 1003,
        "token-expired" => 1004,
        "password-not-found" => 1005,
        "new-password-must-be-different" => 1006,
        "invalid-credentials" => 1007,
        "invalid-function-arguments" => 1008,
        "end-date-before-start-date" => 1009,
        "access-denied" => 1010,
        "invalid-input" => 1011,
        "duplicate-voucher-code" => 1012,
        "voucher-code-not-found" => 1013,
        "invalid-enum" => 1014,
        "invalid-team-member-count" => 1015,
        'db-fail-to-save' => 1016,
        'user-exists' => 1017,
        "team-not-found" => 1018,
        "have-paid" => 1019,
        "duplicate-email-team" => 1020,
        "voucher-limit-reached" => 1021,
        "team-has-applied-voucher" => 1022,
        "team-has-uploaded-bukti-bayar" => 1023,
        "invalid-voucher-apply-date" => 1024,
        "no-access-to-team" => 1025,
        "user-has-active-ticket" => 1026,
        "failed-to-save-file" => 1027,
		"payment-closed" => 1028,
		"payment-verified" => 1029,
    ],
];
